services:
  db:
    image: mysql:8.0
    container_name: marketplace-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=marketplace
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=STRICT_TRANS_TABLES"]
volumes:
  db_data:
